#!/usr/bin/env bash
# Remove files generated by agent-config.
set -euo pipefail

SCRIPT_NAME="uninstall"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=common.sh
source "$REPO_ROOT/scripts/common.sh"

usage() {
  cat <<'USAGE'
Usage: ./scripts/uninstall.sh [--skills|--rules] [--all|--cursor|--claude|--agents]

Remove generated skills and rules. Only this repo's symlinks and managed rule files are removed.
USAGE
}

WANTS_SKILLS=0
WANTS_RULES=0
ARTIFACT_FLAGS=0
WANTS_CURSOR=0
WANTS_CLAUDE=0
WANTS_AGENTS=0
TARGET_FLAGS=0
ALL_TARGETS=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skills) WANTS_SKILLS=1; ARTIFACT_FLAGS=$((ARTIFACT_FLAGS + 1)) ;;
    --rules) WANTS_RULES=1; ARTIFACT_FLAGS=$((ARTIFACT_FLAGS + 1)) ;;
    --all) ALL_TARGETS=1 ;;
    --cursor) WANTS_CURSOR=1; TARGET_FLAGS=$((TARGET_FLAGS + 1)) ;;
    --claude) WANTS_CLAUDE=1; TARGET_FLAGS=$((TARGET_FLAGS + 1)) ;;
    --agents|--codex) WANTS_AGENTS=1; TARGET_FLAGS=$((TARGET_FLAGS + 1)) ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
  shift
done

[[ $ALL_TARGETS -eq 0 || $TARGET_FLAGS -eq 0 ]] || die "--all cannot be combined with an agent target"
[[ $ARTIFACT_FLAGS -ne 0 ]] || { WANTS_SKILLS=1; WANTS_RULES=1; }
if [[ $ALL_TARGETS -eq 1 || $TARGET_FLAGS -eq 0 ]]; then
  WANTS_CLAUDE=1
  WANTS_AGENTS=1
fi

remove_skill_links_from_root() {
  local root="$1" path skill_name src dest_dir dest target marker_source
  [[ -d "$root" ]] || return 0
  info "target $root"
  read_manifest_file "$SKILLS_MANIFEST" SKILLS
  for path in "${SKILLS[@]}"; do
    skill_name="${path##*/}"
    src="$SKILLS_ROOT/$path/SKILL.md"
    dest_dir="$root/$skill_name"
    dest="$dest_dir/SKILL.md"
    if [[ -L "$dest" ]]; then
      target="$(readlink "$dest")"
      if [[ "$target" == "$REPO_ROOT"/* ]]; then
        rm "$dest"
        rmdir "$dest_dir" 2>/dev/null || true
        info "removed $skill_name from $root"
      fi
    elif [[ -f "$dest" && -f "$dest_dir/$MANAGED_SKILL_MARKER" ]]; then
      marker_source="$(<"$dest_dir/$MANAGED_SKILL_MARKER")"
      if [[ "$marker_source" == "$src" ]]; then
        rm "$dest" "$dest_dir/$MANAGED_SKILL_MARKER"
        rmdir "$dest_dir" 2>/dev/null || true
        info "removed $skill_name from $root"
      fi
    fi
  done
}

remove_managed_file() {
  local dest="$1"
  if is_managed_rule_file "$dest"; then
    rm "$dest"
    info "removed $dest"
  fi
}

remove_managed_rules_in_dir() {
  local dir="$1" ext="$2" f
  [[ -d "$dir" ]] || return 0
  info "target $dir"
  for f in "$dir"/*."$ext"; do
    [[ -e "$f" || -L "$f" ]] || continue
    remove_managed_file "$f"
  done
}

if [[ $WANTS_SKILLS -eq 1 ]]; then
  [[ $WANTS_CURSOR -eq 0 ]] || remove_skill_links_from_root "$CURSOR_SKILLS"
  [[ $WANTS_CLAUDE -eq 0 ]] || remove_skill_links_from_root "$CLAUDE_SKILLS"
  [[ $WANTS_AGENTS -eq 0 ]] || remove_skill_links_from_root "$CODEX_SKILLS"
fi
if [[ $WANTS_RULES -eq 1 ]]; then
  [[ $WANTS_CURSOR -eq 0 ]] || remove_managed_rules_in_dir "$CURSOR_RULES" mdc
  [[ $WANTS_CLAUDE -eq 0 ]] || { remove_managed_rules_in_dir "$CLAUDE_RULES" md; remove_managed_file "$CLAUDE_MD"; }
  [[ $WANTS_AGENTS -eq 0 ]] || { info "target $CODEX_AGENTS"; remove_managed_file "$CODEX_AGENTS"; }
fi

info "done"
